### ISSUE TITLE
About g^r

### ISSUE THREAD

**Issue by YLINR** [xlcetc/cryptogm#2]
![image](https://user-images.githubusercontent.com/61904283/123428556-85e64b00-d5f8-11eb-8c7d-de97c1cd8579.png)
这个函数是做乘法吗，如果是的话为什么能表示g的r次方？

**Comment by triplewz** [comment]
是做指数运算，可以看下内部实现，这里只是用这个方法名表示GT的指数运算，GT是乘法群

**Comment by LYL20200307** [comment]
再请问一下，如果我想让乘法群中的元素相乘，例如g^2*g^6  ,  有什么方法可以使用呢？直接new(sm9curve.GT).ScalarMult(g,8)可以吗？

**Comment by LYL20200307** [comment]
您好，我提了个新问题，能否再麻烦回答一下，疑惑很久了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xlcetc/cryptogm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月25日(星期三) 下午4:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xlcetc/cryptogm] About g^r (#2)





 
是做指数运算，可以看下内部实现，这里只是用这个方法名表示GT的指数运算，GT是乘法群
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by YLINR** [comment]
> 再请问一下，如果我想让乘法群中的元素相乘，例如g^2*g^6 , 有什么方法可以使用呢？直接new(sm9curve.GT).ScalarMult(g,8)可以吗？

@triplewz

**Comment by triplewz** [comment]
用add，add表示元素乘法
![image](https://user-images.githubusercontent.com/26701280/130935123-a724298b-7417-4a06-b7c7-6b3d3bb8ba92.png)

**Comment by YLINR** [comment]
好的，谢谢
